# Markdown Questions
***
<b> 1. An algorithm is a set of instructions to solve a problem.

<span style='color:Blue'> 2. "6 or $"</span>

<span style='font-family:Georgia'> 3. Semantic error: Code is correct, but does not run as expected. </span>

<span style='background: yellow'> 4. Complexity is the enemy of efficiency! </span> 

### 5. None, else, elif, or, for

In [73]:
# Daniel Austin 
# BBQ Ribs
# Data Scientist

h = str('Howdy, partner!')
print(h)

i = int(34)
print(i)

j = float(20.8)
print(j)

k = ["hammer", "screwdriver", "pliers"]
print(k)

l = ("corn", "pumpkin", "tomato")
print(l)

print("The length of h is ... ", len(h))

print("Element 4 = ", h[3])

Savvy = str("Learning Data Analytics and Python is Awesome!")
print(Savvy)

print(Savvy[5:-23])

print(Savvy.replace("Awesome", "great"))

Savvy = "Learning Data Analytics and Python is Awesome!"
if "Python" in Savvy:
    print("Yes, 'Python' is present.")

Name = "Daniel "
Age = "35 "
Length = "6 ft 1 in "
miniBio = "Hi my name is " + Name + "I am " + Length + "tall and " + Age + "years old today."
print(miniBio)

Age = float(35)
print(Age)

List = ["Daniel", "Data Analytics", 35, 2, "Pensacola, FL"]

List[2] = 36
print("3rd item replaced...", List)


List.append("UMO")
print("New list ... ", List)

List.append("Mount Olive, NC")
List.append("Baylor Univ")
List.append("Waco, TX")

print("New list ... ", List)
      
print(len(List))

del List[5]
print(List)

NewList = List

List2 = List + NewList
print(List2)

simList = ["banana", "pear", "orange", "apple", "strawberry", "coconut"]
simList.sort()
print("Sorted fruits - default", simList)

List3 = simList
print(List2 + List3)

tup1 = (2000, 2004, 2008, 2012, 2016, 2020, 2024)

timesTuple = tup1 * 3

print("\ntimesTuple[11] ... ", timesTuple[11])
w = timesTuple[0]
x = timesTuple[3]
y = timesTuple[5]
z = timesTuple[6]

tup2 = (w, x, y, z)
print(tup2)

print(*tup2)

tup3 = (50,)
print(tup3)

tup5 = tup2 + tup3
print(tup5)

set1 = {"peanut butter", "jelly", "honey"}

set1.add("cherry")
set1.add("banana")
set1.add("grape")
print(set1)

set1.add("Chevy")
print(set1)

set2 = {"couch", "ottoman", "loveseat"}
set3 = set2.union(set1)
print("\n United Sets... \n", set3)

set2.pop()
print(set2)

set1.clear()
print(set1)

set3.discard("jelly")
print(set3)

set3.remove("honey")
print(set3)

raceCar = {
    "driver": "Daniel",
    "make": "Chevy",
    "model": "Caprice",
    "year": 1964,
    "horsepower": 350
}

raceCar.get("make")

print(raceCar.keys())

print(raceCar.values())

raceCar2 = raceCar.copy()

raceCar2.pop("model")

print(raceCar2)

raceCar2.clear()
print(raceCar2)

Howdy, partner!
34
20.8
['hammer', 'screwdriver', 'pliers']
('corn', 'pumpkin', 'tomato')
The length of h is ...  15
Element 4 =  d
Learning Data Analytics and Python is Awesome!
ing Data Analytics
Learning Data Analytics and Python is great!
Yes, 'Python' is present.
Hi my name is Daniel I am 6 ft 1 in tall and 35 years old today.
35.0
3rd item replaced... ['Daniel', 'Data Analytics', 36, 2, 'Pensacola, FL']
New list ...  ['Daniel', 'Data Analytics', 36, 2, 'Pensacola, FL', 'UMO']
New list ...  ['Daniel', 'Data Analytics', 36, 2, 'Pensacola, FL', 'UMO', 'Mount Olive, NC', 'Baylor Univ', 'Waco, TX']
9
['Daniel', 'Data Analytics', 36, 2, 'Pensacola, FL', 'Mount Olive, NC', 'Baylor Univ', 'Waco, TX']
['Daniel', 'Data Analytics', 36, 2, 'Pensacola, FL', 'Mount Olive, NC', 'Baylor Univ', 'Waco, TX', 'Daniel', 'Data Analytics', 36, 2, 'Pensacola, FL', 'Mount Olive, NC', 'Baylor Univ', 'Waco, TX']
Sorted fruits - default ['apple', 'banana', 'coconut', 'orange', 'pear', 'strawberry']
['Daniel', 'Data Analytics', 36, 2, 'Pensacola, FL', 'Mount Olive, NC', 'Baylor Univ', 'Waco, TX', 'Daniel', 'Data Analytics', 36, 2, 'Pensacola, FL', 'Mount Olive, NC', 'Baylor Univ', 'Waco, TX', 'apple', 'banana', 'coconut', 'orange', 'pear', 'strawberry']

timesTuple[11] ...  2016
(2000, 2012, 2020, 2024)
2000 2012 2020 2024
(50,)
(2000, 2012, 2020, 2024, 50)
{'cherry', 'jelly', 'banana', 'peanut butter', 'honey', 'grape'}
{'cherry', 'jelly', 'banana', 'peanut butter', 'honey', 'Chevy', 'grape'}

 United Sets...
 {'cherry', 'couch', 'jelly', 'banana', 'peanut butter', 'honey', 'loveseat', 'ottoman', 'Chevy', 'grape'}
{'ottoman', 'couch'}
set()
{'cherry', 'couch', 'banana', 'peanut butter', 'honey', 'loveseat', 'ottoman', 'Chevy', 'grape'}
{'cherry', 'couch', 'banana', 'peanut butter', 'loveseat', 'ottoman', 'Chevy', 'grape'}
dict_keys(['driver', 'make', 'model', 'year', 'horsepower'])
dict_values(['Daniel', 'Chevy', 'Caprice', 1964, 350])
{'driver': 'Daniel', 'make': 'Chevy', 'year': 1964, 'horsepower': 350}
{}